name: Build Equibop XBPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'template'
      - 'build-xbps.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Used only for act testing
    # env:
    #   XBPS_ALLOW_CHROOT_BREAKOUT: yes
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install static XBPS tools (Ubuntu to Void Bridge)
        run: |
          wget https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          sudo tar xf xbps-static-latest.x86_64-musl.tar.xz -C /
          xbps-query -V

      - name: Patch Ubuntu DNS for musl resolver
        run: |
          sudo rm -f /etc/resolv.conf
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf

      - name: Disable AppArmor User Namespace Restriction (Ubuntu 24.04 fix)
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Clone void-packages
        run: git clone https://github.com/void-linux/void-packages.git --depth 1

      - name: Prepare void-packages environment
        run: |
          cd void-packages
          ./xbps-src binary-bootstrap
          echo "XBPS_ALLOW_RESTRICTED=yes" >> etc/conf

      - name: Inject template
        run: |
          mkdir -p void-packages/srcpkgs/equibop
          cp template void-packages/srcpkgs/equibop/

      - name: Build package
        run: |
          cd void-packages
          ./xbps-src pkg equibop

      - name: Publish to Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: 'Latest Equibop Build'
          make_latest: true
          files: void-packages/hostdir/binpkgs/nonfree/**/*.xbps
